WIDTH = 1080
HEIGHT = 540
SIZE = (WIDTH, HEIGHT)
FPS = 30
TITLE = "Mario"
TILE_SIZE = 16

CLOUDS_SPEED = 20  # px/s
WALK_SPEED = 100
JUMP_SPEED = 300
FALL_ACCEL = 15  # px/s^2
FALL_MAX = 400

MAX_TILE_ANIMATION_TIMER = 0.15  # s
MAX_PLAYER_ANIMATION_TIMER = 0.1

MAP_FILE = "map.tmx"
SKY_FILE = "sky.png"
CLOUDS_FILE = "clouds.png"
IDLE_DIR = "player/idle"
WALK_DIR = "player/walk"
SPIKE_DIR = "spike"
WATER_DIR = "water"
